basic:
  image: gitlab-registry.mpcdf.mpg.de/mpcdf/module-image
  tags:
    - cloud
    - 1core
  before_script:
    - module load anaconda/3/2023.03
  script:
    - pip3 install --user -e .
    - mkdir test
    - pushd test
    - ~/.local/bin/cnd --help
    - ~/.local/bin/cnd --dryrun init
    - touch Miniforge3-Linux-x86_64.sh
    - ~/.local/bin/cnd init
    - ~/.local/bin/cnd --dryrun build
    - ~/.local/bin/cnd --dryrun build --steps 1,2,3,7
    - ~/.local/bin/cnd --dryrun mount
    - ~/.local/bin/cnd --dryrun umount
    - ~/.local/bin/cnd --dryrun exec -- python3
    - popd
  only:
    - master
