basic:
  image: gitlab-registry.mpcdf.mpg.de/mpcdf/module-image
  tags:
    - cloud
    - 1core
  before_script:
    - module load anaconda/3/2021.11
  script:
    - python setup.py develop --user
  only:
    - master
