basic:
  image: gitlab-registry.mpcdf.mpg.de/mpcdf/module-image
  tags:
    - cloud
    - 1core
  before_script:
    - module load anaconda/3/2023.03
  script:
    - pip3 install --user -e .
    - ~/.local/bin/cnd --help
  only:
    - master
